# === CONFIGURACIÓN DE BASE DE DATOS H2 ===
spring.datasource.url=jdbc:h2:file:./tiendadb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# Dialecto de Hibernate para H2
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Permite que Hibernate actualice automáticamente el esquema de la base de datos
spring.jpa.hibernate.ddl-auto=update

# Activar consola web de H2 (accesible en /h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# === CONFIGURACIÓN DEL BOT DE TELEGRAM ===
telegram.bot.username=tdonarosa_bot
telegram.bot.token=8150045450:AAGlZFCJe1Cu7WUGFDOhGPNl-HsBvGZhg5Q
telegram.bot.defaultChatId=123456789 